core/urls.py
from django.urls import path, re_path
from .views import MainPageView, ProductDetailView, CartView, AddToCartView, CartDetailsAPI, ShopView, RemoveFromCartView, check_login_status
from django.conf import settings
from django.conf.urls.static import static
from django.utils.text import slugify

app_name = 'core'
urlpatterns = [

	# Main pages
	path('', MainPageView.as_view(), name='main'),
	path('cart/', CartView.as_view(),name='cart'),
	path('shop/', ShopView.as_view(),name='shop'),
	path('shop/superdeals', ShopView.as_view(), name='shop-superdeals'),

	# SLUG
	re_path(r'product/(?P<product_id>[A-Za-z0-9]{20})/[A-Za-z0-9-]+', ProductDetailView.as_view(), name='product-page'),

	# API
	path('cart/endpoint', CartDetailsAPI.as_view(), name='cart-details-api'),

	# ADD-REMOVE CART
	path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
	path('remove-from-cart/', RemoveFromCartView.as_view(), name='remove-from-cart'),

	# check login
	path('check-login/', check_login_status ,name='check-login'),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce_solo/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import RegisterView, MainLoginView, MainLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', MainLoginView.as_view(), name='login'),
    path('logout/', MainLogoutView.as_view(), name='logout'),
]

core/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


class Product(models.Model):
	LABEL_CHOICES = (
		('BS', 'Best Seller'),
		('N', 'New'),
		('OFS', 'Out of stock'),
		('C', 'Our Choice'),
		('F', 'Featured'),
		('OS', 'On Sale'),
	)

	CATEGORY_CHOICES = (
		('HP', 'Headphones'),
		('MOB', 'Mobile'),
		('TV', 'Television'),
		('PCP', 'Computer Part'),
		('TECH', 'Technology'),
	)

	title = models.CharField(max_length=120)
	description = models.TextField(default='dummy text dummy text dummy text dummy text dummy text')
	category = models.CharField(max_length=4, choices=CATEGORY_CHOICES)

	product_id = models.SlugField(max_length=80, validators=[RegexValidator(regex='[A-Za-z0-9]{20}$')], blank=True, unique=True)

	previous_price = models.IntegerField(blank=True, null=True)
	current_price = models.IntegerField()
	is_deal_of_the_week = models.BooleanField(default=False, null=True)
	is_in_stock = models.BooleanField(default=True)
	image = models.ImageField(default='product_default.jpg', upload_to='products')
	label = models.CharField(max_length=3, choices=LABEL_CHOICES, null=True, blank=True)
	# how_many_sold = models.IntegerField()

	@staticmethod
	def get_deal_of_the_day_items_queryset():
		return Product.objects.filter(is_deal_of_the_week=True)

	@staticmethod
	def get_deal_of_the_day_items_count():
		return Product.get_deal_of_the_day_items_queryset().count()

	@staticmethod
	def get_available_quantity():
		return Product.objects.all().count()

	@staticmethod
	def get_specific_category_queryset(category):
		return Product.objects.filter(category=category)

	@staticmethod
	def get_featured_products_queryset():
		return Product.objects.filter(label='F')

	# def get_how_many_sold(self):
	# 	return self.how_many_sold


class CartItem(models.Model):
	product = models.OneToOneField(Product, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)

	is_ordered = models.BooleanField(default=False)

	def get_quantity(self):
		return self.quantity

	def get_final_price(self):
		return self.quantity * self.product.current_price

	def get_discount(self):
		pass

	def __str__(self):
		return f"{self.product.title}"


class Order(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	items = models.ManyToManyField('CartItem')
	reference_code = models.OneToOneField('ReferenceCode', related_name='product_code', on_delete=models.CASCADE, null=True)

	is_ordered = models.BooleanField(default=False)

	is_being_processed = models.BooleanField(default=False)
	is_delivered = models.BooleanField(default=False)
	is_recieved = models.BooleanField(default=False)
	refund_requested = models.BooleanField(default=False)
	refund_granted = models.BooleanField(default=False)

	def get_item_count(self):
		count = 0
		for i in range(self.items.all().count()):
			count += self.items.all()[i].quantity
		return count

	def get_total(self):
		total = 0
		for i in range(self.items.all().count()):
			total += self.items.all()[i].quantity * self.items.all()[i].product.current_price
		return total

	def __str__(self):
		return f"Order containing { self.get_item_count() } items"


class ReferenceCode(models.Model):
	code = models.CharField(validators=[RegexValidator(regex='[a-zA-Z0-9]{20}$', message='20 A-Z a-z 0-9')], max_length=20)

	def __str__(self):
		return self.code

core/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, HttpResponse
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Product, CartItem, Order
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse


class MainPageView(View):
	def get(self, *args, **kwargs):

		return render(self.request, 'core/index.html', {
			'PRODUCT': Product,
			'featured_products': Product.get_featured_products_queryset(),
			'deal_of_the_day_products': Product.get_deal_of_the_day_items_queryset()
		})


class ShopView(ListView):
	paginate_by = 15
	model = Product
	template_name = 'core/shop.html'
	extra_context = {
		'products_count': Product.objects.count(),		
	}
	
	def get_queryset(self):
		data = self.request.GET
		
		if 'sd' in data:
			return Product.objects.filter(is_deal_of_the_week=True)
		elif 'category' in data:
			return Product.objects.filter(category=self.request.GET['category'])
		else:
			return Product.objects.get_queryset()
			


class ProductDetailView(DetailView):
	model = Product
	template_name = "core/product.html"
	context_object_name = "product"
	slug_field = 'product_id'
	slug_url_kwarg = 'product_id'


class CartView(LoginRequiredMixin, View):
	def get(self, *args, **kwargs):

		total = 0
		for order in Order.objects.filter(user=self.request.user, is_ordered=False):
			total += order.get_total()

		return render(self.request, 'core/cart.html', {
			'orders': Order.objects.filter(user=self.request.user, is_ordered=False).all(),
			'ORDER_TOTAL': total,

		})


class AddToCartView(LoginRequiredMixin, View):
	def post(self, *args, **kwargs):
		print(self.request.POST)
		try:
			product_id = self.request.POST['product_id']
		except:
			return redirect('/')

		product = Product.objects.get(product_id=product_id)
		order_qs = Order.objects.filter(user=self.request.user, is_ordered=False)
		print('working here')
		if order_qs.exists():
			order = order_qs[0]
			# he has an existing order we must check if there's an item we added in it
			try:
				cart_item = order.items.get(product=product, is_ordered=False)
				cart_item.quantity += 1
				cart_item.save()
				order.save()
				print('2nd part')
				# QUANTITY INCREASE ( USE AJAX TO RAISE IT IN FRONT END )
				return JsonResponse({
					'quantity': str(cart_item.quantity),
					'cart_item_total': str(cart_item.get_final_price()),
					'order_total': str(order.get_total())
				})

			except ObjectDoesNotExist:
				cart_item = CartItem.objects.create(product=product)
				cart_item.save()
				order.items.add(cart_item)
				order.save()
				print('3rd part')
				# CART ITEM CREATED
				return HttpResponse('CTC', status=204)
		else:
			order = Order.objects.create(user=self.request.user)
			cart_item = CartItem.objects.create(product=product)
			order.items.add(cart_item)
			cart_item.save()
			order.save()
			# ORDER CREATED , USE AJAX TO BLA BLA BLA
			print('4th part')
			return HttpResponse('CTC', status=204)


class RemoveFromCartView(LoginRequiredMixin, View):
	def post(self, *args, **kwargs):
		print(self.request.POST)
		try:
			product_id = self.request.POST['product_id']
		except:
			return redirect('/')

		product = Product.objects.get(product_id=product_id)
		order_qs = Order.objects.filter(user=self.request.user, is_ordered=False)
		if order_qs.exists():
			order = order_qs[0]
			cart_item = order.items.get(product=product, is_ordered=False)
			print('working')
			if cart_item.quantity == 1:
				print('2')
				cart_item.delete()
				order.save()
				# delete item from cart
				return JsonResponse({'quantity': '0', 'order_total': str(order.get_total()),})
			else:
				print('2')
				cart_item.quantity -= 1
				cart_item.save()
				order.save()
				return JsonResponse({
					'quantity': str(cart_item.quantity),
					'cart_item_total': str(cart_item.get_final_price()),
					'order_total': str(order.get_total())
				})
		else:
			return HttpResponse('No order')


class CartDetailsAPI(LoginRequiredMixin, View):
	def get(self, *args, **kwargs):
		if self.request.user.is_authenticated:
			order_qs = Order.objects.filter(user=self.request.user, is_ordered=False)
			if order_qs.exists():
				data = {
					'order_total': order_qs[0].get_total(),
					'cart_count': order_qs[0].get_item_count(),
					'ip': self.request.META
				}
				return JsonResponse(data)


def check_login_status(request):
	if request.method == 'GET':
		if request.user.is_authenticated:
			return JsonResponse({'logged_in': True})
		else: 
			return JsonResponse({'logged_in': False})

core/templates/core/blog_single.html
{% extends 'core/index.html' %}
{% load static %}

{% block extra_head %}
	<link rel="stylesheet" type="text/css" href="styles/blog_single_styles.css">
	<link rel="stylesheet" type="text/css" href="styles/blog_single_responsive.css">
{% endblock extra_head %}


<div class="super_container">
	
	<!-- Header -->
	{% include 'header.html' %}
	<!-- End Header -->

	<!-- Home -->

	<div class="home">
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="images/blog_single_background.jpg" data-speed="0.8"></div>
	</div>

	<!-- Single Blog Post -->

	<div class="single_post">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2">
					<div class="single_post_title">Vivamus sed nunc in arcu cursus mollis quis et orci. Interdum et malesuada</div>
					<div class="single_post_text">
						<p>Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin. Praesent at tempus lectus, eleifend blandit felis. Fusce augue arcu, consequat a nisl aliquet, consectetur elementum turpis. Donec iaculis lobortis nisl, et viverra risus imperdiet eu. Etiam mollis posuere elit non sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis arcu a magna sodales venenatis. Integer non diam sit amet magna luctus mollis ac eu nisi. In accumsan tellus ut dapibus blandit.</p>

						<div class="single_post_quote text-center">
							<div class="quote_image"><img src="images/quote.png" alt=""></div>
							<div class="quote_text">Quisque sagittis non ex eget vestibulum. Sed nec ultrices dui. Cras et sagittis erat. Maecenas pulvinar, turpis in dictum tincidunt, dolor nibh lacinia lacus.</div>
							<div class="quote_name">Liam Neeson</div>
						</div>

						<p>Praesent ac magna sed massa euismod congue vitae vitae risus. Nulla lorem augue, mollis non est et, eleifend elementum ante. Nunc id pharetra magna.  Praesent vel orci ornare, blandit mi sed, aliquet nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Blog Posts -->

	<div class="blog">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="blog_posts d-flex flex-row align-items-start justify-content-between">

						<!-- Blog post -->
						<div class="blog_post">
							<div class="blog_image" style="background-image:url(images/blog_4.jpg)"></div>
							<div class="blog_text">Etiam leo nibh, consectetur nec orci et, tempus tempus ex</div>
							<div class="blog_button"><a href="blog_single.html">Continue Reading</a></div>
						</div>

						<!-- Blog post -->
						<div class="blog_post">
							<div class="blog_image" style="background-image:url(images/blog_5.jpg)"></div>
							<div class="blog_text">Sed viverra pellentesque dictum. Aenean ligula justo, viverra in lacus porttitor</div>
							<div class="blog_button"><a href="blog_single.html">Continue Reading</a></div>
						</div>

						<!-- Blog post -->
						<div class="blog_post">
							<div class="blog_image" style="background-image:url(images/blog_6.jpg)"></div>
							<div class="blog_text">In nisl tortor, tempus nec ex vitae, bibendum rutrum mi. Integer tempus nisi</div>
							<div class="blog_button"><a href="blog_single.html">Continue Reading</a></div>
						</div>

					</div>
				</div>	
			</div>
		</div>
	</div>

	<!-- Newsletter -->
	{% include 'newsletter.html' %}
	<!-- End Newsletter -->

	<!-- Footer -->
		{% include 'footer.html' %}
	<!-- End Footer -->

	<!-- Copyright -->
		{% include 'copyright.html' %}
	<!-- End Copyright -->

</div>
{% block extra_scripts %}
	<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
	<script src="{% static 'js/blog_single_custom.js' %}"></script>
{% endblock extra_scripts %}

core/templates/core/scripts.html
{% load static %}

<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.plugins.min.js"></script>

<script>

	function UpdateCartUI(iterator, response){
		$('.cart_item_count').get(iterator).innerText = response['quantity'];
        $('.cart_item_total_price').get(iterator).innerText = response['cart_item_total'];
        $('.order_total_amount').get(0).innerText = response['order_total'];
	}

	function UpdateNAVBAR(){
     $.ajax({
        url: '{% url 'core:cart-details-api' %}',
        type: 'GET',
        success: function (response) {
	        $('.cart_price').get(0).innerText = response['order_total'];
	        $('.cart_count span').get(0).innerText = response['cart_count'];

        }
    });
	}
	$('.lazy').Lazy({
		scrollDirection: 'vertical',
		effect: 'fadeIn',
	})

</script>

core/templates/core/shop.html
{% extends 'core/index.html' %}
{% load static %}


{% block extra_head %}
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/jquery-ui-1.12.1.custom/jquery-ui.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/shop_styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/shop_responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'core_css/shop_styles.css' %}">
{% endblock extra_head %}


{% block content %}
<div class="super_container">
	
	<!-- Header -->
	{% include 'header.html' %}
	<!-- End Header -->

	<!-- Home -->

	<div class="home">
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/shop_background.jpg' %}"></div>
		<div class="home_overlay"></div>
		<div class="home_content d-flex flex-column align-items-center justify-content-center">
			<h2 class="home_title">All Tech gadgets at one place</h2>
		</div>
	</div>

	<!-- Shop -->
	<p> {{ ip }} </p>
	<div class="shop">
		<div class="container">
			<div class="row">
				<div class="col-lg-3">

					<!-- Shop Sidebar -->
					<div class="shop_sidebar">
						<div class="sidebar_section">
							<div class="sidebar_title">Categories</div>
							<ul class="sidebar_categories">
								<li><a href="{% url 'core:shop' %}">Computers & Laptops</a></li>
								<li><a href="#">Cameras & Photos</a></li>
								<li><a href="{% url 'core:shop' %}?category=PCP">Hardware</a></li>

								<li><a href="{% url 'core:shop' %}?category=MOB">Smartphones & Tablets</a></li>
								<li><a href="{% url 'core:shop' %}?category=TV">TV & Audio</a></li>
								<li><a href="{% url 'core:shop' %}?category=TECHNOLOGY">Gadgets</a></li>
								<li><a href="{% url 'core:shop' %}?category=">Car Electronics</a></li>
								<li><a href="{% url 'core:shop' %}?category=">Video Games & Consoles</a></li>
								<li><a href="{% url 'core:shop' %}?category=">Accessories</a></li>
							</ul>
						</div>
						<div class="sidebar_section filter_by_section">
							<div class="sidebar_title">Filter By</div>
							<div class="sidebar_subtitle">Price</div>
							<div class="filter_price">
								<div id="slider-range" class="slider_range"></div>
								<p>Range: </p>
								<p><input type="text" id="amount" class="amount" readonly style="border:0; font-weight:bold;"></p>
							</div>
						</div>
						<div class="sidebar_section">
							<div class="sidebar_subtitle color_subtitle">Color</div>
							<ul class="colors_list">
								<li class="color"><a href="#" style="background: #b19c83;"></a></li>
								<li class="color"><a href="#" style="background: #000000;"></a></li>
								<li class="color"><a href="#" style="background: #999999;"></a></li>
								<li class="color"><a href="#" style="background: #0e8ce4;"></a></li>
								<li class="color"><a href="#" style="background: #df3b3b;"></a></li>
								<li class="color"><a href="#" style="background: #ffffff; border: solid 1px #e1e1e1;"></a></li>
							</ul>
						</div>
						<div class="sidebar_section">
							<div class="sidebar_subtitle brands_subtitle">Brands</div>
							<ul class="brands_list">
								<li class="brand"><a href="#">Apple</a></li>
								<li class="brand"><a href="#">Beoplay</a></li>
								<li class="brand"><a href="#">Google</a></li>
								<li class="brand"><a href="#">Meizu</a></li>
								<li class="brand"><a href="#">OnePlus</a></li>
								<li class="brand"><a href="#">Samsung</a></li>
								<li class="brand"><a href="#">Sony</a></li>
								<li class="brand"><a href="#">Xiaomi</a></li>
							</ul>
						</div>
					</div>

				</div>

				<div class="col-lg-9">
					
					<!-- Shop Content -->

					<div class="shop_content">
						<div class="shop_bar clearfix">
							<div class="shop_product_count">Showing <span>{{ product_list.count }}</span> product out of <span>{{ products_count }}</span></div>
							<div class="shop_sorting">
								<span>Sort by:</span>
								<ul>
									<li>
										<span class="sorting_text">highest rated<i class="fas fa-chevron-down"></i></span>
										<ul>
											<li class="shop_sorting_button" data-isotope-option='{ "sortBy": "original-order" }'>highest rated</li>
											<li class="shop_sorting_button" data-isotope-option='{ "sortBy": "name" }'>name</li>
											<li class="shop_sorting_button" data-isotope-option='{ "sortBy": "price" }'>price</li>
										</ul>
									</li>
								</ul>
							</div>
						</div>
						{# is_new , discount(25) #}
						<div class="product_grid">
							<div class="product_grid_border"></div>


						{% for product in product_list %}
								<!-- Product Item -->
							<div class="product_item is_new">
								<div class="product_border"></div>
								<div class="product_image d-flex flex-column align-items-center justify-content-center"><img class="lazy" src="{{product.image.url}}" alt=""></div>
								<div class="product_content">
									<div class="product_price"><del class="text-muted small">{{ product.previous_price }}</del> {{product.current_price}}</div>
									<div class="product_name"><div><a href="{% url 'core:product-page' product.product_id %}" tabindex="0">{{product.title|truncatechars:'13'}}</a></div></div>
								</div>
								<div class="product_fav"><i class="fas fa-heart"></i></div>
								<ul class="product_marks">
									<li class="product_mark product_discount">-25%</li>
									<li class="product_mark product_new">new</li>
								</ul>

								<button style="max-width: 88%" class="btn btn-primary btn-sm btn-block mt-2">
									<a href="" style="color: white">Add to Cart</a>
								</button>
							</div>

						{% endfor %}

						</div>

					{% if is_paginated %}
						<!-- Shop Page Navigation -->
						<div class="shop_page_nav d-flex flex-row">
						{% if page_obj.has_previous %}
							{% if page_obj.previous_page_number != 1 %}

							<button class="btn page_next d-flex flex-column align-items-center justify-content-center"><a href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-chevron-left"></i></a></button>

							{% endif %}
						{% endif %}

							<ul class="page_nav d-flex flex-row">

								{% if page_obj.has_previous %}
									{% if page_obj.previous_page_number != 1 %}
										<li><a href="?page=1">First</a></li>
										<li><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>

									{% else %}
										<li><a href="?page=1">First</a></li>

									{% endif %}

								{% endif %}
								<li class=""><a>{{ page_obj.number }} </a></li>
								{% if page_obj.has_next %}

									{% if page_obj.number != paginator.num_pages  %}
											<li><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
											<li><a href="?page={{ paginator.num_pages }}">Last</a></li>


									{% endif %}


								{% endif %}
							</ul>

						{% if page_obj.has_next %}
							{% if page_obj.number != paginator.num_pages %}
								<button class="btn page_next d-flex flex-column align-items-center justify-content-center"><a class="" href="?page={{ page_obj.next_page_number }}" ><i class="fas fa-chevron-right"></i></a></button>
							{% endif %}

						{% endif %}

						</div>

					{% endif  %}

					</div>

				</div>
			</div>
		</div>
	</div>

	<!-- Recently Viewed -->

	<div class="viewed">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="viewed_title_container">
						<h3 class="viewed_title">Recently Viewed</h3>
						<div class="viewed_nav_container">
							<div class="viewed_nav viewed_prev"><i class="fas fa-chevron-left"></i></div>
							<div class="viewed_nav viewed_next"><i class="fas fa-chevron-right"></i></div>
						</div>
					</div>

					<div class="viewed_slider_container">
						
						<!-- Recently Viewed Slider -->

						<div class="owl-carousel owl-theme viewed_slider">
							
							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item discount d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="{% static 'images/view_1.jpg' %}" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$225<span>$300</span></div>
										<div class="viewed_name"><a href="#">Beoplay H7</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="{% static 'images/view_2.jpg' %}" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$379</div>
										<div class="viewed_name"><a href="#">LUNA Smartphone</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="{% static 'images/view_3.jpg' %}" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$225</div>
										<div class="viewed_name"><a href="#">Samsung J730F...</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item is_new d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="{% static 'images/view_4.jpg' %}" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$379</div>
										<div class="viewed_name"><a href="#">Huawei MediaPad...</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item discount d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="{% static 'images/view_5.jpg' %}" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$225<span>$300</span></div>
										<div class="viewed_name"><a href="#">Sony PS4 Slim</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>

							<!-- Recently Viewed Item -->
							<div class="owl-item">
								<div class="viewed_item d-flex flex-column align-items-center justify-content-center text-center">
									<div class="viewed_image"><img src="{% static 'images/view_6.jpg' %}" alt=""></div>
									<div class="viewed_content text-center">
										<div class="viewed_price">$375</div>
										<div class="viewed_name"><a href="#">Speedlink...</a></div>
									</div>
									<ul class="item_marks">
										<li class="item_mark item_discount">-25%</li>
										<li class="item_mark item_new">new</li>
									</ul>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- Brands -->
	{% include 'brands.html' %}
	<!-- End Brands -->

	<!-- Newsletter -->
	{% include 'newsletter.html' %}
	<!-- End Newsletter -->

	<!-- Footer -->
		{% include 'footer.html' %}
	<!-- End Footer -->

	<!-- Copyright -->
		{% include 'copyright.html' %}
	<!-- End Copyright -->
</div>
{% endblock content %}


{% block extra_scripts %}
	<script src="{% static 'plugins/Isotope/isotope.pkgd.min.js' %}"></script>
	<script src="{% static 'plugins/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
	<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
	<script src="{% static 'js/shop_custom.js' %}"></script>
{% endblock extra_scripts %}